/*
 * This file is generated by jOOQ.
 */
package com.tracelyp.model.tables;


import com.tracelyp.model.DefaultSchema;
import com.tracelyp.model.Keys;
import com.tracelyp.model.tables.records.CallPathsRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CallPaths extends TableImpl<CallPathsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>call_paths</code>
     */
    public static final CallPaths CALL_PATHS = new CallPaths();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CallPathsRecord> getRecordType() {
        return CallPathsRecord.class;
    }

    /**
     * The column <code>call_paths.id</code>.
     */
    public final TableField<CallPathsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>call_paths.parent_id</code>.
     */
    public final TableField<CallPathsRecord, Long> PARENT_ID = createField(DSL.name("parent_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>call_paths.symbol_id</code>.
     */
    public final TableField<CallPathsRecord, Long> SYMBOL_ID = createField(DSL.name("symbol_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>call_paths.ip</code>.
     */
    public final TableField<CallPathsRecord, Long> IP = createField(DSL.name("ip"), SQLDataType.BIGINT, this, "");

    private CallPaths(Name alias, Table<CallPathsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CallPaths(Name alias, Table<CallPathsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>call_paths</code> table reference
     */
    public CallPaths(String alias) {
        this(DSL.name(alias), CALL_PATHS);
    }

    /**
     * Create an aliased <code>call_paths</code> table reference
     */
    public CallPaths(Name alias) {
        this(alias, CALL_PATHS);
    }

    /**
     * Create a <code>call_paths</code> table reference
     */
    public CallPaths() {
        this(DSL.name("call_paths"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<CallPathsRecord> getPrimaryKey() {
        return Keys.CALL_PATHS__PK_CALL_PATHS;
    }

    @Override
    public CallPaths as(String alias) {
        return new CallPaths(DSL.name(alias), this);
    }

    @Override
    public CallPaths as(Name alias) {
        return new CallPaths(alias, this);
    }

    @Override
    public CallPaths as(Table<?> alias) {
        return new CallPaths(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CallPaths rename(String name) {
        return new CallPaths(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CallPaths rename(Name name) {
        return new CallPaths(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CallPaths rename(Table<?> name) {
        return new CallPaths(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CallPaths where(Condition condition) {
        return new CallPaths(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CallPaths where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CallPaths where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CallPaths where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CallPaths where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CallPaths where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CallPaths where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CallPaths where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CallPaths whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CallPaths whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
