/*
 * This file is generated by jOOQ.
 */
package com.tracelyp.model.tables;


import com.tracelyp.model.DefaultSchema;
import com.tracelyp.model.tables.records.CommThreadsViewRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommThreadsView extends TableImpl<CommThreadsViewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>comm_threads_view</code>
     */
    public static final CommThreadsView COMM_THREADS_VIEW = new CommThreadsView();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CommThreadsViewRecord> getRecordType() {
        return CommThreadsViewRecord.class;
    }

    /**
     * The column <code>comm_threads_view.comm_id</code>.
     */
    public final TableField<CommThreadsViewRecord, Long> COMM_ID = createField(DSL.name("comm_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>comm_threads_view.command</code>.
     */
    public final TableField<CommThreadsViewRecord, String> COMMAND = createField(DSL.name("command"), SQLDataType.VARCHAR(16), this, "");

    /**
     * The column <code>comm_threads_view.thread_id</code>.
     */
    public final TableField<CommThreadsViewRecord, Long> THREAD_ID = createField(DSL.name("thread_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>comm_threads_view.pid</code>.
     */
    public final TableField<CommThreadsViewRecord, Integer> PID = createField(DSL.name("pid"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>comm_threads_view.tid</code>.
     */
    public final TableField<CommThreadsViewRecord, Integer> TID = createField(DSL.name("tid"), SQLDataType.INTEGER, this, "");

    private CommThreadsView(Name alias, Table<CommThreadsViewRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CommThreadsView(Name alias, Table<CommThreadsViewRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("CREATE VIEW comm_threads_view AS SELECT comm_id,(SELECT comm FROM comms WHERE id = comm_id) AS command,thread_id,(SELECT pid FROM threads WHERE id = thread_id) AS pid,(SELECT tid FROM threads WHERE id = thread_id) AS tid FROM comm_threads"), where);
    }

    /**
     * Create an aliased <code>comm_threads_view</code> table reference
     */
    public CommThreadsView(String alias) {
        this(DSL.name(alias), COMM_THREADS_VIEW);
    }

    /**
     * Create an aliased <code>comm_threads_view</code> table reference
     */
    public CommThreadsView(Name alias) {
        this(alias, COMM_THREADS_VIEW);
    }

    /**
     * Create a <code>comm_threads_view</code> table reference
     */
    public CommThreadsView() {
        this(DSL.name("comm_threads_view"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public CommThreadsView as(String alias) {
        return new CommThreadsView(DSL.name(alias), this);
    }

    @Override
    public CommThreadsView as(Name alias) {
        return new CommThreadsView(alias, this);
    }

    @Override
    public CommThreadsView as(Table<?> alias) {
        return new CommThreadsView(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CommThreadsView rename(String name) {
        return new CommThreadsView(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CommThreadsView rename(Name name) {
        return new CommThreadsView(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CommThreadsView rename(Table<?> name) {
        return new CommThreadsView(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CommThreadsView where(Condition condition) {
        return new CommThreadsView(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CommThreadsView where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CommThreadsView where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CommThreadsView where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CommThreadsView where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CommThreadsView where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CommThreadsView where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CommThreadsView where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CommThreadsView whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CommThreadsView whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
