/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class CallPaths(
    val id: Int? = null,
    val parentId: Long? = null,
    val symbolId: Long? = null,
    val ip: Long? = null
): Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: CallPaths = other as CallPaths
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.parentId == null) {
            if (o.parentId != null)
                return false
        }
        else if (this.parentId != o.parentId)
            return false
        if (this.symbolId == null) {
            if (o.symbolId != null)
                return false
        }
        else if (this.symbolId != o.symbolId)
            return false
        if (this.ip == null) {
            if (o.ip != null)
                return false
        }
        else if (this.ip != o.ip)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.parentId == null) 0 else this.parentId.hashCode())
        result = prime * result + (if (this.symbolId == null) 0 else this.symbolId.hashCode())
        result = prime * result + (if (this.ip == null) 0 else this.ip.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("CallPaths (")

        sb.append(id)
        sb.append(", ").append(parentId)
        sb.append(", ").append(symbolId)
        sb.append(", ").append(ip)

        sb.append(")")
        return sb.toString()
    }
}
