/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Cbr(
    val id: Int? = null,
    val cbr: Int? = null,
    val mhz: Int? = null,
    val percent: Int? = null
): Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Cbr = other as Cbr
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.cbr == null) {
            if (o.cbr != null)
                return false
        }
        else if (this.cbr != o.cbr)
            return false
        if (this.mhz == null) {
            if (o.mhz != null)
                return false
        }
        else if (this.mhz != o.mhz)
            return false
        if (this.percent == null) {
            if (o.percent != null)
                return false
        }
        else if (this.percent != o.percent)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.cbr == null) 0 else this.cbr.hashCode())
        result = prime * result + (if (this.mhz == null) 0 else this.mhz.hashCode())
        result = prime * result + (if (this.percent == null) 0 else this.percent.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Cbr (")

        sb.append(id)
        sb.append(", ").append(cbr)
        sb.append(", ").append(mhz)
        sb.append(", ").append(percent)

        sb.append(")")
        return sb.toString()
    }
}
