/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Comms(
    val id: Int? = null,
    val comm: String? = null,
    val cThreadId: Long? = null,
    val cTime: Long? = null,
    val execFlag: Boolean? = null,
    val hasCalls: Boolean? = null
): Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Comms = other as Comms
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.comm == null) {
            if (o.comm != null)
                return false
        }
        else if (this.comm != o.comm)
            return false
        if (this.cThreadId == null) {
            if (o.cThreadId != null)
                return false
        }
        else if (this.cThreadId != o.cThreadId)
            return false
        if (this.cTime == null) {
            if (o.cTime != null)
                return false
        }
        else if (this.cTime != o.cTime)
            return false
        if (this.execFlag == null) {
            if (o.execFlag != null)
                return false
        }
        else if (this.execFlag != o.execFlag)
            return false
        if (this.hasCalls == null) {
            if (o.hasCalls != null)
                return false
        }
        else if (this.hasCalls != o.hasCalls)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.comm == null) 0 else this.comm.hashCode())
        result = prime * result + (if (this.cThreadId == null) 0 else this.cThreadId.hashCode())
        result = prime * result + (if (this.cTime == null) 0 else this.cTime.hashCode())
        result = prime * result + (if (this.execFlag == null) 0 else this.execFlag.hashCode())
        result = prime * result + (if (this.hasCalls == null) 0 else this.hasCalls.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Comms (")

        sb.append(id)
        sb.append(", ").append(comm)
        sb.append(", ").append(cThreadId)
        sb.append(", ").append(cTime)
        sb.append(", ").append(execFlag)
        sb.append(", ").append(hasCalls)

        sb.append(")")
        return sb.toString()
    }
}
