/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class ContextSwitches(
    val id: Int? = null,
    val machineId: Long? = null,
    val time: Long? = null,
    val cpu: Int? = null,
    val threadOutId: Long? = null,
    val commOutId: Long? = null,
    val threadInId: Long? = null,
    val commInId: Long? = null,
    val flags: Int? = null
): Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: ContextSwitches = other as ContextSwitches
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.machineId == null) {
            if (o.machineId != null)
                return false
        }
        else if (this.machineId != o.machineId)
            return false
        if (this.time == null) {
            if (o.time != null)
                return false
        }
        else if (this.time != o.time)
            return false
        if (this.cpu == null) {
            if (o.cpu != null)
                return false
        }
        else if (this.cpu != o.cpu)
            return false
        if (this.threadOutId == null) {
            if (o.threadOutId != null)
                return false
        }
        else if (this.threadOutId != o.threadOutId)
            return false
        if (this.commOutId == null) {
            if (o.commOutId != null)
                return false
        }
        else if (this.commOutId != o.commOutId)
            return false
        if (this.threadInId == null) {
            if (o.threadInId != null)
                return false
        }
        else if (this.threadInId != o.threadInId)
            return false
        if (this.commInId == null) {
            if (o.commInId != null)
                return false
        }
        else if (this.commInId != o.commInId)
            return false
        if (this.flags == null) {
            if (o.flags != null)
                return false
        }
        else if (this.flags != o.flags)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.machineId == null) 0 else this.machineId.hashCode())
        result = prime * result + (if (this.time == null) 0 else this.time.hashCode())
        result = prime * result + (if (this.cpu == null) 0 else this.cpu.hashCode())
        result = prime * result + (if (this.threadOutId == null) 0 else this.threadOutId.hashCode())
        result = prime * result + (if (this.commOutId == null) 0 else this.commOutId.hashCode())
        result = prime * result + (if (this.threadInId == null) 0 else this.threadInId.hashCode())
        result = prime * result + (if (this.commInId == null) 0 else this.commInId.hashCode())
        result = prime * result + (if (this.flags == null) 0 else this.flags.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("ContextSwitches (")

        sb.append(id)
        sb.append(", ").append(machineId)
        sb.append(", ").append(time)
        sb.append(", ").append(cpu)
        sb.append(", ").append(threadOutId)
        sb.append(", ").append(commOutId)
        sb.append(", ").append(threadInId)
        sb.append(", ").append(commInId)
        sb.append(", ").append(flags)

        sb.append(")")
        return sb.toString()
    }
}
