/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Symbols(
    val id: Int? = null,
    val dsoId: Long? = null,
    val symStart: Long? = null,
    val symEnd: Long? = null,
    val binding: Int? = null,
    val name: String? = null
): Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Symbols = other as Symbols
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.dsoId == null) {
            if (o.dsoId != null)
                return false
        }
        else if (this.dsoId != o.dsoId)
            return false
        if (this.symStart == null) {
            if (o.symStart != null)
                return false
        }
        else if (this.symStart != o.symStart)
            return false
        if (this.symEnd == null) {
            if (o.symEnd != null)
                return false
        }
        else if (this.symEnd != o.symEnd)
            return false
        if (this.binding == null) {
            if (o.binding != null)
                return false
        }
        else if (this.binding != o.binding)
            return false
        if (this.name == null) {
            if (o.name != null)
                return false
        }
        else if (this.name != o.name)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.dsoId == null) 0 else this.dsoId.hashCode())
        result = prime * result + (if (this.symStart == null) 0 else this.symStart.hashCode())
        result = prime * result + (if (this.symEnd == null) 0 else this.symEnd.hashCode())
        result = prime * result + (if (this.binding == null) 0 else this.binding.hashCode())
        result = prime * result + (if (this.name == null) 0 else this.name.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Symbols (")

        sb.append(id)
        sb.append(", ").append(dsoId)
        sb.append(", ").append(symStart)
        sb.append(", ").append(symEnd)
        sb.append(", ").append(binding)
        sb.append(", ").append(name)

        sb.append(")")
        return sb.toString()
    }
}
