/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class ThreadsView(
    val id: Int? = null,
    val machineId: Long? = null,
    val hostOrGuest: Any? = null,
    val processId: Long? = null,
    val pid: Int? = null,
    val tid: Int? = null
): Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: ThreadsView = other as ThreadsView
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.machineId == null) {
            if (o.machineId != null)
                return false
        }
        else if (this.machineId != o.machineId)
            return false
        if (this.hostOrGuest == null) {
            if (o.hostOrGuest != null)
                return false
        }
        else if (this.hostOrGuest != o.hostOrGuest)
            return false
        if (this.processId == null) {
            if (o.processId != null)
                return false
        }
        else if (this.processId != o.processId)
            return false
        if (this.pid == null) {
            if (o.pid != null)
                return false
        }
        else if (this.pid != o.pid)
            return false
        if (this.tid == null) {
            if (o.tid != null)
                return false
        }
        else if (this.tid != o.tid)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.machineId == null) 0 else this.machineId.hashCode())
        result = prime * result + (if (this.hostOrGuest == null) 0 else this.hostOrGuest.hashCode())
        result = prime * result + (if (this.processId == null) 0 else this.processId.hashCode())
        result = prime * result + (if (this.pid == null) 0 else this.pid.hashCode())
        result = prime * result + (if (this.tid == null) 0 else this.tid.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("ThreadsView (")

        sb.append(id)
        sb.append(", ").append(machineId)
        sb.append(", ").append(hostOrGuest)
        sb.append(", ").append(processId)
        sb.append(", ").append(pid)
        sb.append(", ").append(tid)

        sb.append(")")
        return sb.toString()
    }
}
