/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables;


import com.perfscope.model.DefaultSchema;
import com.perfscope.model.Keys;
import com.perfscope.model.tables.records.ContextSwitchesRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContextSwitches extends TableImpl<ContextSwitchesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>context_switches</code>
     */
    public static final ContextSwitches CONTEXT_SWITCHES = new ContextSwitches();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContextSwitchesRecord> getRecordType() {
        return ContextSwitchesRecord.class;
    }

    /**
     * The column <code>context_switches.id</code>.
     */
    public final TableField<ContextSwitchesRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>context_switches.machine_id</code>.
     */
    public final TableField<ContextSwitchesRecord, Long> MACHINE_ID = createField(DSL.name("machine_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>context_switches.time</code>.
     */
    public final TableField<ContextSwitchesRecord, Long> TIME = createField(DSL.name("time"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>context_switches.cpu</code>.
     */
    public final TableField<ContextSwitchesRecord, Integer> CPU = createField(DSL.name("cpu"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>context_switches.thread_out_id</code>.
     */
    public final TableField<ContextSwitchesRecord, Long> THREAD_OUT_ID = createField(DSL.name("thread_out_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>context_switches.comm_out_id</code>.
     */
    public final TableField<ContextSwitchesRecord, Long> COMM_OUT_ID = createField(DSL.name("comm_out_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>context_switches.thread_in_id</code>.
     */
    public final TableField<ContextSwitchesRecord, Long> THREAD_IN_ID = createField(DSL.name("thread_in_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>context_switches.comm_in_id</code>.
     */
    public final TableField<ContextSwitchesRecord, Long> COMM_IN_ID = createField(DSL.name("comm_in_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>context_switches.flags</code>.
     */
    public final TableField<ContextSwitchesRecord, Integer> FLAGS = createField(DSL.name("flags"), SQLDataType.INTEGER, this, "");

    private ContextSwitches(Name alias, Table<ContextSwitchesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ContextSwitches(Name alias, Table<ContextSwitchesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>context_switches</code> table reference
     */
    public ContextSwitches(String alias) {
        this(DSL.name(alias), CONTEXT_SWITCHES);
    }

    /**
     * Create an aliased <code>context_switches</code> table reference
     */
    public ContextSwitches(Name alias) {
        this(alias, CONTEXT_SWITCHES);
    }

    /**
     * Create a <code>context_switches</code> table reference
     */
    public ContextSwitches() {
        this(DSL.name("context_switches"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<ContextSwitchesRecord> getPrimaryKey() {
        return Keys.CONTEXT_SWITCHES__PK_CONTEXT_SWITCHES;
    }

    @Override
    public ContextSwitches as(String alias) {
        return new ContextSwitches(DSL.name(alias), this);
    }

    @Override
    public ContextSwitches as(Name alias) {
        return new ContextSwitches(alias, this);
    }

    @Override
    public ContextSwitches as(Table<?> alias) {
        return new ContextSwitches(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContextSwitches rename(String name) {
        return new ContextSwitches(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ContextSwitches rename(Name name) {
        return new ContextSwitches(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ContextSwitches rename(Table<?> name) {
        return new ContextSwitches(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContextSwitches where(Condition condition) {
        return new ContextSwitches(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContextSwitches where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContextSwitches where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContextSwitches where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ContextSwitches where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ContextSwitches where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ContextSwitches where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ContextSwitches where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContextSwitches whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContextSwitches whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
