/*
 * This file is generated by jOOQ.
 */
package com.tracelyp.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Machines implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final Integer pid;
    private final String rootDir;

    public Machines(Machines value) {
        this.id = value.id;
        this.pid = value.pid;
        this.rootDir = value.rootDir;
    }

    public Machines(
        Integer id,
        Integer pid,
        String rootDir
    ) {
        this.id = id;
        this.pid = pid;
        this.rootDir = rootDir;
    }

    /**
     * Getter for <code>machines.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>machines.pid</code>.
     */
    public Integer getPid() {
        return this.pid;
    }

    /**
     * Getter for <code>machines.root_dir</code>.
     */
    public String getRootDir() {
        return this.rootDir;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Machines other = (Machines) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.pid == null) {
            if (other.pid != null)
                return false;
        }
        else if (!this.pid.equals(other.pid))
            return false;
        if (this.rootDir == null) {
            if (other.rootDir != null)
                return false;
        }
        else if (!this.rootDir.equals(other.rootDir))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.pid == null) ? 0 : this.pid.hashCode());
        result = prime * result + ((this.rootDir == null) ? 0 : this.rootDir.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Machines (");

        sb.append(id);
        sb.append(", ").append(pid);
        sb.append(", ").append(rootDir);

        sb.append(")");
        return sb.toString();
    }
}
