/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables.records;


import com.perfscope.model.tables.CallsView;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CallsViewRecord extends TableRecordImpl<CallsViewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>calls_view.id</code>.
     */
    public CallsViewRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>calls_view.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>calls_view.thread_id</code>.
     */
    public CallsViewRecord setThreadId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>calls_view.thread_id</code>.
     */
    public Long getThreadId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>calls_view.pid</code>.
     */
    public CallsViewRecord setPid(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>calls_view.pid</code>.
     */
    public Integer getPid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>calls_view.tid</code>.
     */
    public CallsViewRecord setTid(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>calls_view.tid</code>.
     */
    public Integer getTid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>calls_view.command</code>.
     */
    public CallsViewRecord setCommand(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>calls_view.command</code>.
     */
    public String getCommand() {
        return (String) get(4);
    }

    /**
     * Setter for <code>calls_view.call_path_id</code>.
     */
    public CallsViewRecord setCallPathId(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>calls_view.call_path_id</code>.
     */
    public Long getCallPathId() {
        return (Long) get(5);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public CallsViewRecord setIp(Object value) {
        set(6, value);
        return this;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getIp() {
        return get(6);
    }

    /**
     * Setter for <code>calls_view.symbol_id</code>.
     */
    public CallsViewRecord setSymbolId(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>calls_view.symbol_id</code>.
     */
    public Long getSymbolId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>calls_view.symbol</code>.
     */
    public CallsViewRecord setSymbol(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>calls_view.symbol</code>.
     */
    public String getSymbol() {
        return (String) get(8);
    }

    /**
     * Setter for <code>calls_view.call_time</code>.
     */
    public CallsViewRecord setCallTime(Long value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>calls_view.call_time</code>.
     */
    public Long getCallTime() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>calls_view.return_time</code>.
     */
    public CallsViewRecord setReturnTime(Long value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>calls_view.return_time</code>.
     */
    public Long getReturnTime() {
        return (Long) get(10);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public CallsViewRecord setElapsedTime(Object value) {
        set(11, value);
        return this;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getElapsedTime() {
        return get(11);
    }

    /**
     * Setter for <code>calls_view.branch_count</code>.
     */
    public CallsViewRecord setBranchCount(Long value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>calls_view.branch_count</code>.
     */
    public Long getBranchCount() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>calls_view.insn_count</code>.
     */
    public CallsViewRecord setInsnCount(Long value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>calls_view.insn_count</code>.
     */
    public Long getInsnCount() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>calls_view.cyc_count</code>.
     */
    public CallsViewRecord setCycCount(Long value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>calls_view.cyc_count</code>.
     */
    public Long getCycCount() {
        return (Long) get(14);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public CallsViewRecord setIpc(Object value) {
        set(15, value);
        return this;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getIpc() {
        return get(15);
    }

    /**
     * Setter for <code>calls_view.call_id</code>.
     */
    public CallsViewRecord setCallId(Long value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>calls_view.call_id</code>.
     */
    public Long getCallId() {
        return (Long) get(16);
    }

    /**
     * Setter for <code>calls_view.return_id</code>.
     */
    public CallsViewRecord setReturnId(Long value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>calls_view.return_id</code>.
     */
    public Long getReturnId() {
        return (Long) get(17);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public CallsViewRecord setFlags(Object value) {
        set(18, value);
        return this;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getFlags() {
        return get(18);
    }

    /**
     * Setter for <code>calls_view.parent_call_path_id</code>.
     */
    public CallsViewRecord setParentCallPathId(Long value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>calls_view.parent_call_path_id</code>.
     */
    public Long getParentCallPathId() {
        return (Long) get(19);
    }

    /**
     * Setter for <code>calls_view.parent_id</code>.
     */
    public CallsViewRecord setParentId(Long value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>calls_view.parent_id</code>.
     */
    public Long getParentId() {
        return (Long) get(20);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CallsViewRecord
     */
    public CallsViewRecord() {
        super(CallsView.CALLS_VIEW);
    }

    /**
     * Create a detached, initialised CallsViewRecord
     */
    public CallsViewRecord(Integer id, Long threadId, Integer pid, Integer tid, String command, Long callPathId, Object ip, Long symbolId, String symbol, Long callTime, Long returnTime, Object elapsedTime, Long branchCount, Long insnCount, Long cycCount, Object ipc, Long callId, Long returnId, Object flags, Long parentCallPathId, Long parentId) {
        super(CallsView.CALLS_VIEW);

        setId(id);
        setThreadId(threadId);
        setPid(pid);
        setTid(tid);
        setCommand(command);
        setCallPathId(callPathId);
        setIp(ip);
        setSymbolId(symbolId);
        setSymbol(symbol);
        setCallTime(callTime);
        setReturnTime(returnTime);
        setElapsedTime(elapsedTime);
        setBranchCount(branchCount);
        setInsnCount(insnCount);
        setCycCount(cycCount);
        setIpc(ipc);
        setCallId(callId);
        setReturnId(returnId);
        setFlags(flags);
        setParentCallPathId(parentCallPathId);
        setParentId(parentId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised CallsViewRecord
     */
    public CallsViewRecord(com.perfscope.model.tables.pojos.CallsView value) {
        super(CallsView.CALLS_VIEW);

        if (value != null) {
            setId(value.getId());
            setThreadId(value.getThreadId());
            setPid(value.getPid());
            setTid(value.getTid());
            setCommand(value.getCommand());
            setCallPathId(value.getCallPathId());
            setIp(value.getIp());
            setSymbolId(value.getSymbolId());
            setSymbol(value.getSymbol());
            setCallTime(value.getCallTime());
            setReturnTime(value.getReturnTime());
            setElapsedTime(value.getElapsedTime());
            setBranchCount(value.getBranchCount());
            setInsnCount(value.getInsnCount());
            setCycCount(value.getCycCount());
            setIpc(value.getIpc());
            setCallId(value.getCallId());
            setReturnId(value.getReturnId());
            setFlags(value.getFlags());
            setParentCallPathId(value.getParentCallPathId());
            setParentId(value.getParentId());
            resetChangedOnNotNull();
        }
    }
}
