/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables.records;


import com.perfscope.model.tables.CallPaths;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CallPathsRecord extends UpdatableRecordImpl<CallPathsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>call_paths.id</code>.
     */
    public CallPathsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>call_paths.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>call_paths.parent_id</code>.
     */
    public CallPathsRecord setParentId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>call_paths.parent_id</code>.
     */
    public Long getParentId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>call_paths.symbol_id</code>.
     */
    public CallPathsRecord setSymbolId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>call_paths.symbol_id</code>.
     */
    public Long getSymbolId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>call_paths.ip</code>.
     */
    public CallPathsRecord setIp(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>call_paths.ip</code>.
     */
    public Long getIp() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CallPathsRecord
     */
    public CallPathsRecord() {
        super(CallPaths.CALL_PATHS);
    }

    /**
     * Create a detached, initialised CallPathsRecord
     */
    public CallPathsRecord(Integer id, Long parentId, Long symbolId, Long ip) {
        super(CallPaths.CALL_PATHS);

        setId(id);
        setParentId(parentId);
        setSymbolId(symbolId);
        setIp(ip);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised CallPathsRecord
     */
    public CallPathsRecord(com.perfscope.model.tables.pojos.CallPaths value) {
        super(CallPaths.CALL_PATHS);

        if (value != null) {
            setId(value.getId());
            setParentId(value.getParentId());
            setSymbolId(value.getSymbolId());
            setIp(value.getIp());
            resetChangedOnNotNull();
        }
    }
}
