/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables.records;


import com.perfscope.model.tables.Calls;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CallsRecord extends UpdatableRecordImpl<CallsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>calls.id</code>.
     */
    public CallsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>calls.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>calls.thread_id</code>.
     */
    public CallsRecord setThreadId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>calls.thread_id</code>.
     */
    public Long getThreadId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>calls.comm_id</code>.
     */
    public CallsRecord setCommId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>calls.comm_id</code>.
     */
    public Long getCommId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>calls.call_path_id</code>.
     */
    public CallsRecord setCallPathId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>calls.call_path_id</code>.
     */
    public Long getCallPathId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>calls.call_time</code>.
     */
    public CallsRecord setCallTime(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>calls.call_time</code>.
     */
    public Long getCallTime() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>calls.return_time</code>.
     */
    public CallsRecord setReturnTime(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>calls.return_time</code>.
     */
    public Long getReturnTime() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>calls.branch_count</code>.
     */
    public CallsRecord setBranchCount(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>calls.branch_count</code>.
     */
    public Long getBranchCount() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>calls.call_id</code>.
     */
    public CallsRecord setCallId(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>calls.call_id</code>.
     */
    public Long getCallId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>calls.return_id</code>.
     */
    public CallsRecord setReturnId(Long value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>calls.return_id</code>.
     */
    public Long getReturnId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>calls.parent_call_path_id</code>.
     */
    public CallsRecord setParentCallPathId(Long value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>calls.parent_call_path_id</code>.
     */
    public Long getParentCallPathId() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>calls.flags</code>.
     */
    public CallsRecord setFlags(Integer value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>calls.flags</code>.
     */
    public Integer getFlags() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>calls.parent_id</code>.
     */
    public CallsRecord setParentId(Long value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>calls.parent_id</code>.
     */
    public Long getParentId() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>calls.insn_count</code>.
     */
    public CallsRecord setInsnCount(Long value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>calls.insn_count</code>.
     */
    public Long getInsnCount() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>calls.cyc_count</code>.
     */
    public CallsRecord setCycCount(Long value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>calls.cyc_count</code>.
     */
    public Long getCycCount() {
        return (Long) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CallsRecord
     */
    public CallsRecord() {
        super(Calls.CALLS);
    }

    /**
     * Create a detached, initialised CallsRecord
     */
    public CallsRecord(Integer id, Long threadId, Long commId, Long callPathId, Long callTime, Long returnTime, Long branchCount, Long callId, Long returnId, Long parentCallPathId, Integer flags, Long parentId, Long insnCount, Long cycCount) {
        super(Calls.CALLS);

        setId(id);
        setThreadId(threadId);
        setCommId(commId);
        setCallPathId(callPathId);
        setCallTime(callTime);
        setReturnTime(returnTime);
        setBranchCount(branchCount);
        setCallId(callId);
        setReturnId(returnId);
        setParentCallPathId(parentCallPathId);
        setFlags(flags);
        setParentId(parentId);
        setInsnCount(insnCount);
        setCycCount(cycCount);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised CallsRecord
     */
    public CallsRecord(com.perfscope.model.tables.pojos.Calls value) {
        super(Calls.CALLS);

        if (value != null) {
            setId(value.getId());
            setThreadId(value.getThreadId());
            setCommId(value.getCommId());
            setCallPathId(value.getCallPathId());
            setCallTime(value.getCallTime());
            setReturnTime(value.getReturnTime());
            setBranchCount(value.getBranchCount());
            setCallId(value.getCallId());
            setReturnId(value.getReturnId());
            setParentCallPathId(value.getParentCallPathId());
            setFlags(value.getFlags());
            setParentId(value.getParentId());
            setInsnCount(value.getInsnCount());
            setCycCount(value.getCycCount());
            resetChangedOnNotNull();
        }
    }
}
