/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables.records;


import com.perfscope.model.tables.ContextSwitches;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContextSwitchesRecord extends UpdatableRecordImpl<ContextSwitchesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>context_switches.id</code>.
     */
    public ContextSwitchesRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>context_switches.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>context_switches.machine_id</code>.
     */
    public ContextSwitchesRecord setMachineId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>context_switches.machine_id</code>.
     */
    public Long getMachineId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>context_switches.time</code>.
     */
    public ContextSwitchesRecord setTime(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>context_switches.time</code>.
     */
    public Long getTime() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>context_switches.cpu</code>.
     */
    public ContextSwitchesRecord setCpu(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>context_switches.cpu</code>.
     */
    public Integer getCpu() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>context_switches.thread_out_id</code>.
     */
    public ContextSwitchesRecord setThreadOutId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>context_switches.thread_out_id</code>.
     */
    public Long getThreadOutId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>context_switches.comm_out_id</code>.
     */
    public ContextSwitchesRecord setCommOutId(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>context_switches.comm_out_id</code>.
     */
    public Long getCommOutId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>context_switches.thread_in_id</code>.
     */
    public ContextSwitchesRecord setThreadInId(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>context_switches.thread_in_id</code>.
     */
    public Long getThreadInId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>context_switches.comm_in_id</code>.
     */
    public ContextSwitchesRecord setCommInId(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>context_switches.comm_in_id</code>.
     */
    public Long getCommInId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>context_switches.flags</code>.
     */
    public ContextSwitchesRecord setFlags(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>context_switches.flags</code>.
     */
    public Integer getFlags() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContextSwitchesRecord
     */
    public ContextSwitchesRecord() {
        super(ContextSwitches.CONTEXT_SWITCHES);
    }

    /**
     * Create a detached, initialised ContextSwitchesRecord
     */
    public ContextSwitchesRecord(Integer id, Long machineId, Long time, Integer cpu, Long threadOutId, Long commOutId, Long threadInId, Long commInId, Integer flags) {
        super(ContextSwitches.CONTEXT_SWITCHES);

        setId(id);
        setMachineId(machineId);
        setTime(time);
        setCpu(cpu);
        setThreadOutId(threadOutId);
        setCommOutId(commOutId);
        setThreadInId(threadInId);
        setCommInId(commInId);
        setFlags(flags);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ContextSwitchesRecord
     */
    public ContextSwitchesRecord(com.perfscope.model.tables.pojos.ContextSwitches value) {
        super(ContextSwitches.CONTEXT_SWITCHES);

        if (value != null) {
            setId(value.getId());
            setMachineId(value.getMachineId());
            setTime(value.getTime());
            setCpu(value.getCpu());
            setThreadOutId(value.getThreadOutId());
            setCommOutId(value.getCommOutId());
            setThreadInId(value.getThreadInId());
            setCommInId(value.getCommInId());
            setFlags(value.getFlags());
            resetChangedOnNotNull();
        }
    }
}
