/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables.records;


import com.perfscope.model.tables.ContextSwitchesView;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContextSwitchesViewRecord extends TableRecordImpl<ContextSwitchesViewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>context_switches_view.id</code>.
     */
    public ContextSwitchesViewRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>context_switches_view.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>context_switches_view.machine_id</code>.
     */
    public ContextSwitchesViewRecord setMachineId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>context_switches_view.machine_id</code>.
     */
    public Long getMachineId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>context_switches_view.time</code>.
     */
    public ContextSwitchesViewRecord setTime(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>context_switches_view.time</code>.
     */
    public Long getTime() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>context_switches_view.cpu</code>.
     */
    public ContextSwitchesViewRecord setCpu(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>context_switches_view.cpu</code>.
     */
    public Integer getCpu() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>context_switches_view.pid_out</code>.
     */
    public ContextSwitchesViewRecord setPidOut(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>context_switches_view.pid_out</code>.
     */
    public Integer getPidOut() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>context_switches_view.tid_out</code>.
     */
    public ContextSwitchesViewRecord setTidOut(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>context_switches_view.tid_out</code>.
     */
    public Integer getTidOut() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>context_switches_view.comm_out</code>.
     */
    public ContextSwitchesViewRecord setCommOut(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>context_switches_view.comm_out</code>.
     */
    public String getCommOut() {
        return (String) get(6);
    }

    /**
     * Setter for <code>context_switches_view.pid_in</code>.
     */
    public ContextSwitchesViewRecord setPidIn(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>context_switches_view.pid_in</code>.
     */
    public Integer getPidIn() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>context_switches_view.tid_in</code>.
     */
    public ContextSwitchesViewRecord setTidIn(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>context_switches_view.tid_in</code>.
     */
    public Integer getTidIn() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>context_switches_view.comm_in</code>.
     */
    public ContextSwitchesViewRecord setCommIn(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>context_switches_view.comm_in</code>.
     */
    public String getCommIn() {
        return (String) get(9);
    }

    /**
     * Setter for <code>context_switches_view.flags</code>.
     */
    public ContextSwitchesViewRecord setFlags(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>context_switches_view.flags</code>.
     */
    public String getFlags() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContextSwitchesViewRecord
     */
    public ContextSwitchesViewRecord() {
        super(ContextSwitchesView.CONTEXT_SWITCHES_VIEW);
    }

    /**
     * Create a detached, initialised ContextSwitchesViewRecord
     */
    public ContextSwitchesViewRecord(Integer id, Long machineId, Long time, Integer cpu, Integer pidOut, Integer tidOut, String commOut, Integer pidIn, Integer tidIn, String commIn, String flags) {
        super(ContextSwitchesView.CONTEXT_SWITCHES_VIEW);

        setId(id);
        setMachineId(machineId);
        setTime(time);
        setCpu(cpu);
        setPidOut(pidOut);
        setTidOut(tidOut);
        setCommOut(commOut);
        setPidIn(pidIn);
        setTidIn(tidIn);
        setCommIn(commIn);
        setFlags(flags);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ContextSwitchesViewRecord
     */
    public ContextSwitchesViewRecord(com.perfscope.model.tables.pojos.ContextSwitchesView value) {
        super(ContextSwitchesView.CONTEXT_SWITCHES_VIEW);

        if (value != null) {
            setId(value.getId());
            setMachineId(value.getMachineId());
            setTime(value.getTime());
            setCpu(value.getCpu());
            setPidOut(value.getPidOut());
            setTidOut(value.getTidOut());
            setCommOut(value.getCommOut());
            setPidIn(value.getPidIn());
            setTidIn(value.getTidIn());
            setCommIn(value.getCommIn());
            setFlags(value.getFlags());
            resetChangedOnNotNull();
        }
    }
}
