/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables.records;


import com.perfscope.model.tables.SelectedEvents;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SelectedEventsRecord extends UpdatableRecordImpl<SelectedEventsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>selected_events.id</code>.
     */
    public SelectedEventsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>selected_events.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>selected_events.name</code>.
     */
    public SelectedEventsRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>selected_events.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SelectedEventsRecord
     */
    public SelectedEventsRecord() {
        super(SelectedEvents.SELECTED_EVENTS);
    }

    /**
     * Create a detached, initialised SelectedEventsRecord
     */
    public SelectedEventsRecord(Integer id, String name) {
        super(SelectedEvents.SELECTED_EVENTS);

        setId(id);
        setName(name);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised SelectedEventsRecord
     */
    public SelectedEventsRecord(com.perfscope.model.tables.pojos.SelectedEvents value) {
        super(SelectedEvents.SELECTED_EVENTS);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            resetChangedOnNotNull();
        }
    }
}
