/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables.records;


import com.perfscope.model.tables.Symbols;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SymbolsRecord extends UpdatableRecordImpl<SymbolsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>symbols.id</code>.
     */
    public SymbolsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>symbols.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>symbols.dso_id</code>.
     */
    public SymbolsRecord setDsoId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>symbols.dso_id</code>.
     */
    public Long getDsoId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>symbols.sym_start</code>.
     */
    public SymbolsRecord setSymStart(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>symbols.sym_start</code>.
     */
    public Long getSymStart() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>symbols.sym_end</code>.
     */
    public SymbolsRecord setSymEnd(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>symbols.sym_end</code>.
     */
    public Long getSymEnd() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>symbols.binding</code>.
     */
    public SymbolsRecord setBinding(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>symbols.binding</code>.
     */
    public Integer getBinding() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>symbols.name</code>.
     */
    public SymbolsRecord setName(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>symbols.name</code>.
     */
    public String getName() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SymbolsRecord
     */
    public SymbolsRecord() {
        super(Symbols.SYMBOLS);
    }

    /**
     * Create a detached, initialised SymbolsRecord
     */
    public SymbolsRecord(Integer id, Long dsoId, Long symStart, Long symEnd, Integer binding, String name) {
        super(Symbols.SYMBOLS);

        setId(id);
        setDsoId(dsoId);
        setSymStart(symStart);
        setSymEnd(symEnd);
        setBinding(binding);
        setName(name);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised SymbolsRecord
     */
    public SymbolsRecord(com.perfscope.model.tables.pojos.Symbols value) {
        super(Symbols.SYMBOLS);

        if (value != null) {
            setId(value.getId());
            setDsoId(value.getDsoId());
            setSymStart(value.getSymStart());
            setSymEnd(value.getSymEnd());
            setBinding(value.getBinding());
            setName(value.getName());
            resetChangedOnNotNull();
        }
    }
}
