/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables


import com.perfscope.model.DefaultSchema
import com.perfscope.model.indexes.PCPID_IDX
import com.perfscope.model.indexes.PID_IDX
import com.perfscope.model.keys.CALLS__PK_CALLS
import com.perfscope.model.tables.records.CallsRecord

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Calls(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CallsRecord>?,
    parentPath: InverseForeignKey<out Record, CallsRecord>?,
    aliased: Table<CallsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CallsRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>calls</code>
         */
        val CALLS: Calls = Calls()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CallsRecord> = CallsRecord::class.java

    /**
     * The column <code>calls.id</code>.
     */
    val ID: TableField<CallsRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>calls.thread_id</code>.
     */
    val THREAD_ID: TableField<CallsRecord, Long?> = createField(DSL.name("thread_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>calls.comm_id</code>.
     */
    val COMM_ID: TableField<CallsRecord, Long?> = createField(DSL.name("comm_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>calls.call_path_id</code>.
     */
    val CALL_PATH_ID: TableField<CallsRecord, Long?> = createField(DSL.name("call_path_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>calls.call_time</code>.
     */
    val CALL_TIME: TableField<CallsRecord, Long?> = createField(DSL.name("call_time"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>calls.return_time</code>.
     */
    val RETURN_TIME: TableField<CallsRecord, Long?> = createField(DSL.name("return_time"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>calls.branch_count</code>.
     */
    val BRANCH_COUNT: TableField<CallsRecord, Long?> = createField(DSL.name("branch_count"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>calls.call_id</code>.
     */
    val CALL_ID: TableField<CallsRecord, Long?> = createField(DSL.name("call_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>calls.return_id</code>.
     */
    val RETURN_ID: TableField<CallsRecord, Long?> = createField(DSL.name("return_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>calls.parent_call_path_id</code>.
     */
    val PARENT_CALL_PATH_ID: TableField<CallsRecord, Long?> = createField(DSL.name("parent_call_path_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>calls.flags</code>.
     */
    val FLAGS: TableField<CallsRecord, Int?> = createField(DSL.name("flags"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>calls.parent_id</code>.
     */
    val PARENT_ID: TableField<CallsRecord, Long?> = createField(DSL.name("parent_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>calls.insn_count</code>.
     */
    val INSN_COUNT: TableField<CallsRecord, Long?> = createField(DSL.name("insn_count"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>calls.cyc_count</code>.
     */
    val CYC_COUNT: TableField<CallsRecord, Long?> = createField(DSL.name("cyc_count"), SQLDataType.BIGINT, this, "")

    private constructor(alias: Name, aliased: Table<CallsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CallsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CallsRecord>?, where: Condition): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>calls</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>calls</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>calls</code> table reference
     */
    constructor(): this(DSL.name("calls"), null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIndexes(): List<Index> = listOf(PCPID_IDX, PID_IDX)
    override fun getPrimaryKey(): UniqueKey<CallsRecord> = CALLS__PK_CALLS
    override fun `as`(alias: String): Calls = Calls(DSL.name(alias), this)
    override fun `as`(alias: Name): Calls = Calls(alias, this)
    override fun `as`(alias: Table<*>): Calls = Calls(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Calls = Calls(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Calls = Calls(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Calls = Calls(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition): Calls = Calls(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Calls = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition): Calls = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>): Calls = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Calls = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Calls = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Calls = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Calls = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Calls = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Calls = where(DSL.notExists(select))
}
