/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables


import com.perfscope.model.DefaultSchema
import com.perfscope.model.keys.CALL_PATHS__PK_CALL_PATHS
import com.perfscope.model.tables.records.CallPathsRecord

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CallPaths(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CallPathsRecord>?,
    parentPath: InverseForeignKey<out Record, CallPathsRecord>?,
    aliased: Table<CallPathsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CallPathsRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>call_paths</code>
         */
        val CALL_PATHS: CallPaths = CallPaths()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CallPathsRecord> = CallPathsRecord::class.java

    /**
     * The column <code>call_paths.id</code>.
     */
    val ID: TableField<CallPathsRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>call_paths.parent_id</code>.
     */
    val PARENT_ID: TableField<CallPathsRecord, Long?> = createField(DSL.name("parent_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>call_paths.symbol_id</code>.
     */
    val SYMBOL_ID: TableField<CallPathsRecord, Long?> = createField(DSL.name("symbol_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>call_paths.ip</code>.
     */
    val IP: TableField<CallPathsRecord, Long?> = createField(DSL.name("ip"), SQLDataType.BIGINT, this, "")

    private constructor(alias: Name, aliased: Table<CallPathsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CallPathsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CallPathsRecord>?, where: Condition): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>call_paths</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>call_paths</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>call_paths</code> table reference
     */
    constructor(): this(DSL.name("call_paths"), null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getPrimaryKey(): UniqueKey<CallPathsRecord> = CALL_PATHS__PK_CALL_PATHS
    override fun `as`(alias: String): CallPaths = CallPaths(DSL.name(alias), this)
    override fun `as`(alias: Name): CallPaths = CallPaths(alias, this)
    override fun `as`(alias: Table<*>): CallPaths = CallPaths(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CallPaths = CallPaths(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CallPaths = CallPaths(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): CallPaths = CallPaths(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition): CallPaths = CallPaths(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): CallPaths = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition): CallPaths = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>): CallPaths = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): CallPaths = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): CallPaths = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): CallPaths = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): CallPaths = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): CallPaths = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): CallPaths = where(DSL.notExists(select))
}
