/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables


import com.perfscope.model.DefaultSchema
import com.perfscope.model.keys.CBR__PK_CBR
import com.perfscope.model.tables.records.CbrRecord

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Cbr(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CbrRecord>?,
    parentPath: InverseForeignKey<out Record, CbrRecord>?,
    aliased: Table<CbrRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CbrRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>cbr</code>
         */
        val CBR: Cbr = Cbr()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CbrRecord> = CbrRecord::class.java

    /**
     * The column <code>cbr.id</code>.
     */
    val ID: TableField<CbrRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>cbr.cbr</code>.
     */
    val CBR_: TableField<CbrRecord, Int?> = createField(DSL.name("cbr"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>cbr.mhz</code>.
     */
    val MHZ: TableField<CbrRecord, Int?> = createField(DSL.name("mhz"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>cbr.percent</code>.
     */
    val PERCENT: TableField<CbrRecord, Int?> = createField(DSL.name("percent"), SQLDataType.INTEGER, this, "")

    private constructor(alias: Name, aliased: Table<CbrRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CbrRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CbrRecord>?, where: Condition): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>cbr</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>cbr</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>cbr</code> table reference
     */
    constructor(): this(DSL.name("cbr"), null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getPrimaryKey(): UniqueKey<CbrRecord> = CBR__PK_CBR
    override fun `as`(alias: String): Cbr = Cbr(DSL.name(alias), this)
    override fun `as`(alias: Name): Cbr = Cbr(alias, this)
    override fun `as`(alias: Table<*>): Cbr = Cbr(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Cbr = Cbr(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Cbr = Cbr(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Cbr = Cbr(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition): Cbr = Cbr(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Cbr = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition): Cbr = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>): Cbr = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Cbr = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Cbr = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Cbr = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Cbr = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Cbr = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Cbr = where(DSL.notExists(select))
}
