/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables


import com.perfscope.model.DefaultSchema
import com.perfscope.model.tables.records.CbrViewRecord

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CbrView(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CbrViewRecord>?,
    parentPath: InverseForeignKey<out Record, CbrViewRecord>?,
    aliased: Table<CbrViewRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CbrViewRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.view("CREATE VIEW cbr_view AS SELECT cbr.id,time,cpu,cbr,mhz,percent FROM cbr INNER JOIN samples ON samples.id = cbr.id"),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>cbr_view</code>
         */
        val CBR_VIEW: CbrView = CbrView()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CbrViewRecord> = CbrViewRecord::class.java

    /**
     * The column <code>cbr_view.id</code>.
     */
    val ID: TableField<CbrViewRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>cbr_view.time</code>.
     */
    val TIME: TableField<CbrViewRecord, Long?> = createField(DSL.name("time"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>cbr_view.cpu</code>.
     */
    val CPU: TableField<CbrViewRecord, Int?> = createField(DSL.name("cpu"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>cbr_view.cbr</code>.
     */
    val CBR: TableField<CbrViewRecord, Int?> = createField(DSL.name("cbr"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>cbr_view.mhz</code>.
     */
    val MHZ: TableField<CbrViewRecord, Int?> = createField(DSL.name("mhz"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>cbr_view.percent</code>.
     */
    val PERCENT: TableField<CbrViewRecord, Int?> = createField(DSL.name("percent"), SQLDataType.INTEGER, this, "")

    private constructor(alias: Name, aliased: Table<CbrViewRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CbrViewRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CbrViewRecord>?, where: Condition): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>cbr_view</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>cbr_view</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>cbr_view</code> table reference
     */
    constructor(): this(DSL.name("cbr_view"), null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun `as`(alias: String): CbrView = CbrView(DSL.name(alias), this)
    override fun `as`(alias: Name): CbrView = CbrView(alias, this)
    override fun `as`(alias: Table<*>): CbrView = CbrView(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CbrView = CbrView(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CbrView = CbrView(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): CbrView = CbrView(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition): CbrView = CbrView(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): CbrView = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition): CbrView = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>): CbrView = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): CbrView = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): CbrView = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): CbrView = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): CbrView = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): CbrView = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): CbrView = where(DSL.notExists(select))
}
