/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables


import com.perfscope.model.DefaultSchema
import com.perfscope.model.keys.CONTEXT_SWITCHES__PK_CONTEXT_SWITCHES
import com.perfscope.model.tables.records.ContextSwitchesRecord

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ContextSwitches(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ContextSwitchesRecord>?,
    parentPath: InverseForeignKey<out Record, ContextSwitchesRecord>?,
    aliased: Table<ContextSwitchesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<ContextSwitchesRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>context_switches</code>
         */
        val CONTEXT_SWITCHES: ContextSwitches = ContextSwitches()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ContextSwitchesRecord> = ContextSwitchesRecord::class.java

    /**
     * The column <code>context_switches.id</code>.
     */
    val ID: TableField<ContextSwitchesRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>context_switches.machine_id</code>.
     */
    val MACHINE_ID: TableField<ContextSwitchesRecord, Long?> = createField(DSL.name("machine_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>context_switches.time</code>.
     */
    val TIME: TableField<ContextSwitchesRecord, Long?> = createField(DSL.name("time"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>context_switches.cpu</code>.
     */
    val CPU: TableField<ContextSwitchesRecord, Int?> = createField(DSL.name("cpu"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>context_switches.thread_out_id</code>.
     */
    val THREAD_OUT_ID: TableField<ContextSwitchesRecord, Long?> = createField(DSL.name("thread_out_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>context_switches.comm_out_id</code>.
     */
    val COMM_OUT_ID: TableField<ContextSwitchesRecord, Long?> = createField(DSL.name("comm_out_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>context_switches.thread_in_id</code>.
     */
    val THREAD_IN_ID: TableField<ContextSwitchesRecord, Long?> = createField(DSL.name("thread_in_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>context_switches.comm_in_id</code>.
     */
    val COMM_IN_ID: TableField<ContextSwitchesRecord, Long?> = createField(DSL.name("comm_in_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>context_switches.flags</code>.
     */
    val FLAGS: TableField<ContextSwitchesRecord, Int?> = createField(DSL.name("flags"), SQLDataType.INTEGER, this, "")

    private constructor(alias: Name, aliased: Table<ContextSwitchesRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<ContextSwitchesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<ContextSwitchesRecord>?, where: Condition): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>context_switches</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>context_switches</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>context_switches</code> table reference
     */
    constructor(): this(DSL.name("context_switches"), null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getPrimaryKey(): UniqueKey<ContextSwitchesRecord> = CONTEXT_SWITCHES__PK_CONTEXT_SWITCHES
    override fun `as`(alias: String): ContextSwitches = ContextSwitches(DSL.name(alias), this)
    override fun `as`(alias: Name): ContextSwitches = ContextSwitches(alias, this)
    override fun `as`(alias: Table<*>): ContextSwitches = ContextSwitches(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ContextSwitches = ContextSwitches(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ContextSwitches = ContextSwitches(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): ContextSwitches = ContextSwitches(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition): ContextSwitches = ContextSwitches(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): ContextSwitches = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition): ContextSwitches = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>): ContextSwitches = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): ContextSwitches = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): ContextSwitches = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): ContextSwitches = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): ContextSwitches = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): ContextSwitches = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): ContextSwitches = where(DSL.notExists(select))
}
