/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables


import com.perfscope.model.DefaultSchema
import com.perfscope.model.tables.records.DsosViewRecord

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DsosView(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, DsosViewRecord>?,
    parentPath: InverseForeignKey<out Record, DsosViewRecord>?,
    aliased: Table<DsosViewRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<DsosViewRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.view("CREATE VIEW dsos_view AS SELECT id,machine_id,(SELECT host_or_guest FROM machines_view WHERE id = machine_id) AS host_or_guest,short_name,long_name,build_id FROM dsos"),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>dsos_view</code>
         */
        val DSOS_VIEW: DsosView = DsosView()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<DsosViewRecord> = DsosViewRecord::class.java

    /**
     * The column <code>dsos_view.id</code>.
     */
    val ID: TableField<DsosViewRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>dsos_view.machine_id</code>.
     */
    val MACHINE_ID: TableField<DsosViewRecord, Long?> = createField(DSL.name("machine_id"), SQLDataType.BIGINT, this, "")
    @Deprecated(message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.")
    val HOST_OR_GUEST: TableField<DsosViewRecord, Any?> = createField(DSL.name("host_or_guest"), SQLDataType.OTHER, this, "")

    /**
     * The column <code>dsos_view.short_name</code>.
     */
    val SHORT_NAME: TableField<DsosViewRecord, String?> = createField(DSL.name("short_name"), SQLDataType.VARCHAR(256), this, "")

    /**
     * The column <code>dsos_view.long_name</code>.
     */
    val LONG_NAME: TableField<DsosViewRecord, String?> = createField(DSL.name("long_name"), SQLDataType.VARCHAR(4096), this, "")

    /**
     * The column <code>dsos_view.build_id</code>.
     */
    val BUILD_ID: TableField<DsosViewRecord, String?> = createField(DSL.name("build_id"), SQLDataType.VARCHAR(64), this, "")

    private constructor(alias: Name, aliased: Table<DsosViewRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<DsosViewRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<DsosViewRecord>?, where: Condition): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>dsos_view</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>dsos_view</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>dsos_view</code> table reference
     */
    constructor(): this(DSL.name("dsos_view"), null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun `as`(alias: String): DsosView = DsosView(DSL.name(alias), this)
    override fun `as`(alias: Name): DsosView = DsosView(alias, this)
    override fun `as`(alias: Table<*>): DsosView = DsosView(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): DsosView = DsosView(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): DsosView = DsosView(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): DsosView = DsosView(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition): DsosView = DsosView(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): DsosView = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition): DsosView = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>): DsosView = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): DsosView = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): DsosView = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): DsosView = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): DsosView = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): DsosView = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): DsosView = where(DSL.notExists(select))
}
