/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables


import com.perfscope.model.DefaultSchema
import com.perfscope.model.keys.SAMPLES__PK_SAMPLES
import com.perfscope.model.tables.records.SamplesRecord

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Samples(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, SamplesRecord>?,
    parentPath: InverseForeignKey<out Record, SamplesRecord>?,
    aliased: Table<SamplesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<SamplesRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>samples</code>
         */
        val SAMPLES: Samples = Samples()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<SamplesRecord> = SamplesRecord::class.java

    /**
     * The column <code>samples.id</code>.
     */
    val ID: TableField<SamplesRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>samples.evsel_id</code>.
     */
    val EVSEL_ID: TableField<SamplesRecord, Long?> = createField(DSL.name("evsel_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>samples.machine_id</code>.
     */
    val MACHINE_ID: TableField<SamplesRecord, Long?> = createField(DSL.name("machine_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>samples.thread_id</code>.
     */
    val THREAD_ID: TableField<SamplesRecord, Long?> = createField(DSL.name("thread_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>samples.comm_id</code>.
     */
    val COMM_ID: TableField<SamplesRecord, Long?> = createField(DSL.name("comm_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>samples.dso_id</code>.
     */
    val DSO_ID: TableField<SamplesRecord, Long?> = createField(DSL.name("dso_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>samples.symbol_id</code>.
     */
    val SYMBOL_ID: TableField<SamplesRecord, Long?> = createField(DSL.name("symbol_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>samples.sym_offset</code>.
     */
    val SYM_OFFSET: TableField<SamplesRecord, Long?> = createField(DSL.name("sym_offset"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>samples.ip</code>.
     */
    val IP: TableField<SamplesRecord, Long?> = createField(DSL.name("ip"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>samples.time</code>.
     */
    val TIME: TableField<SamplesRecord, Long?> = createField(DSL.name("time"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>samples.cpu</code>.
     */
    val CPU: TableField<SamplesRecord, Int?> = createField(DSL.name("cpu"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>samples.to_dso_id</code>.
     */
    val TO_DSO_ID: TableField<SamplesRecord, Long?> = createField(DSL.name("to_dso_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>samples.to_symbol_id</code>.
     */
    val TO_SYMBOL_ID: TableField<SamplesRecord, Long?> = createField(DSL.name("to_symbol_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>samples.to_sym_offset</code>.
     */
    val TO_SYM_OFFSET: TableField<SamplesRecord, Long?> = createField(DSL.name("to_sym_offset"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>samples.to_ip</code>.
     */
    val TO_IP: TableField<SamplesRecord, Long?> = createField(DSL.name("to_ip"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>samples.branch_type</code>.
     */
    val BRANCH_TYPE: TableField<SamplesRecord, Int?> = createField(DSL.name("branch_type"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>samples.in_tx</code>.
     */
    val IN_TX: TableField<SamplesRecord, Boolean?> = createField(DSL.name("in_tx"), SQLDataType.BOOLEAN, this, "")

    /**
     * The column <code>samples.call_path_id</code>.
     */
    val CALL_PATH_ID: TableField<SamplesRecord, Long?> = createField(DSL.name("call_path_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>samples.insn_count</code>.
     */
    val INSN_COUNT: TableField<SamplesRecord, Long?> = createField(DSL.name("insn_count"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>samples.cyc_count</code>.
     */
    val CYC_COUNT: TableField<SamplesRecord, Long?> = createField(DSL.name("cyc_count"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>samples.flags</code>.
     */
    val FLAGS: TableField<SamplesRecord, Int?> = createField(DSL.name("flags"), SQLDataType.INTEGER, this, "")

    private constructor(alias: Name, aliased: Table<SamplesRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<SamplesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<SamplesRecord>?, where: Condition): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>samples</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>samples</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>samples</code> table reference
     */
    constructor(): this(DSL.name("samples"), null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getPrimaryKey(): UniqueKey<SamplesRecord> = SAMPLES__PK_SAMPLES
    override fun `as`(alias: String): Samples = Samples(DSL.name(alias), this)
    override fun `as`(alias: Name): Samples = Samples(alias, this)
    override fun `as`(alias: Table<*>): Samples = Samples(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Samples = Samples(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Samples = Samples(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Samples = Samples(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition): Samples = Samples(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Samples = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition): Samples = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>): Samples = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Samples = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Samples = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Samples = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Samples = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Samples = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Samples = where(DSL.notExists(select))
}
