/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables


import com.perfscope.model.DefaultSchema
import com.perfscope.model.keys.SYMBOLS__PK_SYMBOLS
import com.perfscope.model.tables.records.SymbolsRecord

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Symbols(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, SymbolsRecord>?,
    parentPath: InverseForeignKey<out Record, SymbolsRecord>?,
    aliased: Table<SymbolsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<SymbolsRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>symbols</code>
         */
        val SYMBOLS: Symbols = Symbols()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<SymbolsRecord> = SymbolsRecord::class.java

    /**
     * The column <code>symbols.id</code>.
     */
    val ID: TableField<SymbolsRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>symbols.dso_id</code>.
     */
    val DSO_ID: TableField<SymbolsRecord, Long?> = createField(DSL.name("dso_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>symbols.sym_start</code>.
     */
    val SYM_START: TableField<SymbolsRecord, Long?> = createField(DSL.name("sym_start"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>symbols.sym_end</code>.
     */
    val SYM_END: TableField<SymbolsRecord, Long?> = createField(DSL.name("sym_end"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>symbols.binding</code>.
     */
    val BINDING: TableField<SymbolsRecord, Int?> = createField(DSL.name("binding"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>symbols.name</code>.
     */
    val NAME: TableField<SymbolsRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(2048), this, "")

    private constructor(alias: Name, aliased: Table<SymbolsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<SymbolsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<SymbolsRecord>?, where: Condition): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>symbols</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>symbols</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>symbols</code> table reference
     */
    constructor(): this(DSL.name("symbols"), null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getPrimaryKey(): UniqueKey<SymbolsRecord> = SYMBOLS__PK_SYMBOLS
    override fun `as`(alias: String): Symbols = Symbols(DSL.name(alias), this)
    override fun `as`(alias: Name): Symbols = Symbols(alias, this)
    override fun `as`(alias: Table<*>): Symbols = Symbols(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Symbols = Symbols(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Symbols = Symbols(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Symbols = Symbols(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition): Symbols = Symbols(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Symbols = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition): Symbols = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>): Symbols = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Symbols = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Symbols = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Symbols = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Symbols = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Symbols = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Symbols = where(DSL.notExists(select))
}
