/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables


import com.perfscope.model.DefaultSchema
import com.perfscope.model.keys.THREADS__PK_THREADS
import com.perfscope.model.tables.records.ThreadsRecord

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Threads(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ThreadsRecord>?,
    parentPath: InverseForeignKey<out Record, ThreadsRecord>?,
    aliased: Table<ThreadsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<ThreadsRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>threads</code>
         */
        val THREADS: Threads = Threads()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ThreadsRecord> = ThreadsRecord::class.java

    /**
     * The column <code>threads.id</code>.
     */
    val ID: TableField<ThreadsRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>threads.machine_id</code>.
     */
    val MACHINE_ID: TableField<ThreadsRecord, Long?> = createField(DSL.name("machine_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>threads.process_id</code>.
     */
    val PROCESS_ID: TableField<ThreadsRecord, Long?> = createField(DSL.name("process_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>threads.pid</code>.
     */
    val PID: TableField<ThreadsRecord, Int?> = createField(DSL.name("pid"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>threads.tid</code>.
     */
    val TID: TableField<ThreadsRecord, Int?> = createField(DSL.name("tid"), SQLDataType.INTEGER, this, "")

    private constructor(alias: Name, aliased: Table<ThreadsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<ThreadsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<ThreadsRecord>?, where: Condition): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>threads</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>threads</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>threads</code> table reference
     */
    constructor(): this(DSL.name("threads"), null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getPrimaryKey(): UniqueKey<ThreadsRecord> = THREADS__PK_THREADS
    override fun `as`(alias: String): Threads = Threads(DSL.name(alias), this)
    override fun `as`(alias: Name): Threads = Threads(alias, this)
    override fun `as`(alias: Table<*>): Threads = Threads(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Threads = Threads(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Threads = Threads(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Threads = Threads(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition): Threads = Threads(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Threads = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition): Threads = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>): Threads = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Threads = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Threads = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Threads = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Threads = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Threads = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Threads = where(DSL.notExists(select))
}
