/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.indexes


import com.perfscope.model.tables.Calls

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val PCPID_IDX: Index = Internal.createIndex(DSL.name("pcpid_idx"), Calls.CALLS, arrayOf(Calls.CALLS.PARENT_CALL_PATH_ID), false)
val PID_IDX: Index = Internal.createIndex(DSL.name("pid_idx"), Calls.CALLS, arrayOf(Calls.CALLS.PARENT_ID), false)
