/*
 * This file is generated by jOOQ.
 */
package com.tracelyp.model.tables.records;


import com.tracelyp.model.tables.Cbr;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CbrRecord extends UpdatableRecordImpl<CbrRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cbr.id</code>.
     */
    public CbrRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>cbr.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>cbr.cbr</code>.
     */
    public CbrRecord setCbr(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>cbr.cbr</code>.
     */
    public Integer getCbr() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>cbr.mhz</code>.
     */
    public CbrRecord setMhz(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>cbr.mhz</code>.
     */
    public Integer getMhz() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>cbr.percent</code>.
     */
    public CbrRecord setPercent(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>cbr.percent</code>.
     */
    public Integer getPercent() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CbrRecord
     */
    public CbrRecord() {
        super(Cbr.CBR);
    }

    /**
     * Create a detached, initialised CbrRecord
     */
    public CbrRecord(Integer id, Integer cbr, Integer mhz, Integer percent) {
        super(Cbr.CBR);

        setId(id);
        setCbr(cbr);
        setMhz(mhz);
        setPercent(percent);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised CbrRecord
     */
    public CbrRecord(com.tracelyp.model.tables.pojos.Cbr value) {
        super(Cbr.CBR);

        if (value != null) {
            setId(value.getId());
            setCbr(value.getCbr());
            setMhz(value.getMhz());
            setPercent(value.getPercent());
            resetChangedOnNotNull();
        }
    }
}
