/*
 * This file is generated by jOOQ.
 */
package com.tracelyp.model.tables.records;


import com.tracelyp.model.tables.Machines;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MachinesRecord extends UpdatableRecordImpl<MachinesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>machines.id</code>.
     */
    public MachinesRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>machines.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>machines.pid</code>.
     */
    public MachinesRecord setPid(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>machines.pid</code>.
     */
    public Integer getPid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>machines.root_dir</code>.
     */
    public MachinesRecord setRootDir(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>machines.root_dir</code>.
     */
    public String getRootDir() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MachinesRecord
     */
    public MachinesRecord() {
        super(Machines.MACHINES);
    }

    /**
     * Create a detached, initialised MachinesRecord
     */
    public MachinesRecord(Integer id, Integer pid, String rootDir) {
        super(Machines.MACHINES);

        setId(id);
        setPid(pid);
        setRootDir(rootDir);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised MachinesRecord
     */
    public MachinesRecord(com.tracelyp.model.tables.pojos.Machines value) {
        super(Machines.MACHINES);

        if (value != null) {
            setId(value.getId());
            setPid(value.getPid());
            setRootDir(value.getRootDir());
            resetChangedOnNotNull();
        }
    }
}
