/*
 * This file is generated by jOOQ.
 */
package com.tracelyp.model.tables.records;


import com.tracelyp.model.tables.SamplesView;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SamplesViewRecord extends TableRecordImpl<SamplesViewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>samples_view.id</code>.
     */
    public SamplesViewRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>samples_view.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>samples_view.time</code>.
     */
    public SamplesViewRecord setTime(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>samples_view.time</code>.
     */
    public Long getTime() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>samples_view.cpu</code>.
     */
    public SamplesViewRecord setCpu(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>samples_view.cpu</code>.
     */
    public Integer getCpu() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>samples_view.pid</code>.
     */
    public SamplesViewRecord setPid(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>samples_view.pid</code>.
     */
    public Integer getPid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>samples_view.tid</code>.
     */
    public SamplesViewRecord setTid(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>samples_view.tid</code>.
     */
    public Integer getTid() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>samples_view.command</code>.
     */
    public SamplesViewRecord setCommand(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>samples_view.command</code>.
     */
    public String getCommand() {
        return (String) get(5);
    }

    /**
     * Setter for <code>samples_view.event</code>.
     */
    public SamplesViewRecord setEvent(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>samples_view.event</code>.
     */
    public String getEvent() {
        return (String) get(6);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public SamplesViewRecord setIpHex(Object value) {
        set(7, value);
        return this;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getIpHex() {
        return get(7);
    }

    /**
     * Setter for <code>samples_view.symbol</code>.
     */
    public SamplesViewRecord setSymbol(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>samples_view.symbol</code>.
     */
    public String getSymbol() {
        return (String) get(8);
    }

    /**
     * Setter for <code>samples_view.sym_offset</code>.
     */
    public SamplesViewRecord setSymOffset(Long value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>samples_view.sym_offset</code>.
     */
    public Long getSymOffset() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>samples_view.dso_short_name</code>.
     */
    public SamplesViewRecord setDsoShortName(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>samples_view.dso_short_name</code>.
     */
    public String getDsoShortName() {
        return (String) get(10);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public SamplesViewRecord setToIpHex(Object value) {
        set(11, value);
        return this;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getToIpHex() {
        return get(11);
    }

    /**
     * Setter for <code>samples_view.to_symbol</code>.
     */
    public SamplesViewRecord setToSymbol(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>samples_view.to_symbol</code>.
     */
    public String getToSymbol() {
        return (String) get(12);
    }

    /**
     * Setter for <code>samples_view.to_sym_offset</code>.
     */
    public SamplesViewRecord setToSymOffset(Long value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>samples_view.to_sym_offset</code>.
     */
    public Long getToSymOffset() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>samples_view.to_dso_short_name</code>.
     */
    public SamplesViewRecord setToDsoShortName(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>samples_view.to_dso_short_name</code>.
     */
    public String getToDsoShortName() {
        return (String) get(14);
    }

    /**
     * Setter for <code>samples_view.branch_type_name</code>.
     */
    public SamplesViewRecord setBranchTypeName(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>samples_view.branch_type_name</code>.
     */
    public String getBranchTypeName() {
        return (String) get(15);
    }

    /**
     * Setter for <code>samples_view.in_tx</code>.
     */
    public SamplesViewRecord setInTx(Boolean value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>samples_view.in_tx</code>.
     */
    public Boolean getInTx() {
        return (Boolean) get(16);
    }

    /**
     * Setter for <code>samples_view.insn_count</code>.
     */
    public SamplesViewRecord setInsnCount(Long value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>samples_view.insn_count</code>.
     */
    public Long getInsnCount() {
        return (Long) get(17);
    }

    /**
     * Setter for <code>samples_view.cyc_count</code>.
     */
    public SamplesViewRecord setCycCount(Long value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>samples_view.cyc_count</code>.
     */
    public Long getCycCount() {
        return (Long) get(18);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public SamplesViewRecord setIpc(Object value) {
        set(19, value);
        return this;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getIpc() {
        return get(19);
    }

    /**
     * Setter for <code>samples_view.flags</code>.
     */
    public SamplesViewRecord setFlags(Integer value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>samples_view.flags</code>.
     */
    public Integer getFlags() {
        return (Integer) get(20);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SamplesViewRecord
     */
    public SamplesViewRecord() {
        super(SamplesView.SAMPLES_VIEW);
    }

    /**
     * Create a detached, initialised SamplesViewRecord
     */
    public SamplesViewRecord(Integer id, Long time, Integer cpu, Integer pid, Integer tid, String command, String event, Object ipHex, String symbol, Long symOffset, String dsoShortName, Object toIpHex, String toSymbol, Long toSymOffset, String toDsoShortName, String branchTypeName, Boolean inTx, Long insnCount, Long cycCount, Object ipc, Integer flags) {
        super(SamplesView.SAMPLES_VIEW);

        setId(id);
        setTime(time);
        setCpu(cpu);
        setPid(pid);
        setTid(tid);
        setCommand(command);
        setEvent(event);
        setIpHex(ipHex);
        setSymbol(symbol);
        setSymOffset(symOffset);
        setDsoShortName(dsoShortName);
        setToIpHex(toIpHex);
        setToSymbol(toSymbol);
        setToSymOffset(toSymOffset);
        setToDsoShortName(toDsoShortName);
        setBranchTypeName(branchTypeName);
        setInTx(inTx);
        setInsnCount(insnCount);
        setCycCount(cycCount);
        setIpc(ipc);
        setFlags(flags);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised SamplesViewRecord
     */
    public SamplesViewRecord(com.tracelyp.model.tables.pojos.SamplesView value) {
        super(SamplesView.SAMPLES_VIEW);

        if (value != null) {
            setId(value.getId());
            setTime(value.getTime());
            setCpu(value.getCpu());
            setPid(value.getPid());
            setTid(value.getTid());
            setCommand(value.getCommand());
            setEvent(value.getEvent());
            setIpHex(value.getIpHex());
            setSymbol(value.getSymbol());
            setSymOffset(value.getSymOffset());
            setDsoShortName(value.getDsoShortName());
            setToIpHex(value.getToIpHex());
            setToSymbol(value.getToSymbol());
            setToSymOffset(value.getToSymOffset());
            setToDsoShortName(value.getToDsoShortName());
            setBranchTypeName(value.getBranchTypeName());
            setInTx(value.getInTx());
            setInsnCount(value.getInsnCount());
            setCycCount(value.getCycCount());
            setIpc(value.getIpc());
            setFlags(value.getFlags());
            resetChangedOnNotNull();
        }
    }
}
