/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model;


import com.perfscope.model.tables.BranchTypes;
import com.perfscope.model.tables.CallPaths;
import com.perfscope.model.tables.CallPathsView;
import com.perfscope.model.tables.Calls;
import com.perfscope.model.tables.CallsView;
import com.perfscope.model.tables.Cbr;
import com.perfscope.model.tables.CbrView;
import com.perfscope.model.tables.CommThreads;
import com.perfscope.model.tables.CommThreadsView;
import com.perfscope.model.tables.Comms;
import com.perfscope.model.tables.ContextSwitches;
import com.perfscope.model.tables.ContextSwitchesView;
import com.perfscope.model.tables.Dsos;
import com.perfscope.model.tables.DsosView;
import com.perfscope.model.tables.Machines;
import com.perfscope.model.tables.MachinesView;
import com.perfscope.model.tables.Samples;
import com.perfscope.model.tables.SamplesView;
import com.perfscope.model.tables.SelectedEvents;
import com.perfscope.model.tables.Symbols;
import com.perfscope.model.tables.SymbolsView;
import com.perfscope.model.tables.Threads;
import com.perfscope.model.tables.ThreadsView;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>branch_types</code>.
     */
    public static final BranchTypes BRANCH_TYPES = BranchTypes.BRANCH_TYPES;

    /**
     * The table <code>call_paths</code>.
     */
    public static final CallPaths CALL_PATHS = CallPaths.CALL_PATHS;

    /**
     * The table <code>call_paths_view</code>.
     */
    public static final CallPathsView CALL_PATHS_VIEW = CallPathsView.CALL_PATHS_VIEW;

    /**
     * The table <code>calls</code>.
     */
    public static final Calls CALLS = Calls.CALLS;

    /**
     * The table <code>calls_view</code>.
     */
    public static final CallsView CALLS_VIEW = CallsView.CALLS_VIEW;

    /**
     * The table <code>cbr</code>.
     */
    public static final Cbr CBR = Cbr.CBR;

    /**
     * The table <code>cbr_view</code>.
     */
    public static final CbrView CBR_VIEW = CbrView.CBR_VIEW;

    /**
     * The table <code>comm_threads</code>.
     */
    public static final CommThreads COMM_THREADS = CommThreads.COMM_THREADS;

    /**
     * The table <code>comm_threads_view</code>.
     */
    public static final CommThreadsView COMM_THREADS_VIEW = CommThreadsView.COMM_THREADS_VIEW;

    /**
     * The table <code>comms</code>.
     */
    public static final Comms COMMS = Comms.COMMS;

    /**
     * The table <code>context_switches</code>.
     */
    public static final ContextSwitches CONTEXT_SWITCHES = ContextSwitches.CONTEXT_SWITCHES;

    /**
     * The table <code>context_switches_view</code>.
     */
    public static final ContextSwitchesView CONTEXT_SWITCHES_VIEW = ContextSwitchesView.CONTEXT_SWITCHES_VIEW;

    /**
     * The table <code>dsos</code>.
     */
    public static final Dsos DSOS = Dsos.DSOS;

    /**
     * The table <code>dsos_view</code>.
     */
    public static final DsosView DSOS_VIEW = DsosView.DSOS_VIEW;

    /**
     * The table <code>machines</code>.
     */
    public static final Machines MACHINES = Machines.MACHINES;

    /**
     * The table <code>machines_view</code>.
     */
    public static final MachinesView MACHINES_VIEW = MachinesView.MACHINES_VIEW;

    /**
     * The table <code>samples</code>.
     */
    public static final Samples SAMPLES = Samples.SAMPLES;

    /**
     * The table <code>samples_view</code>.
     */
    public static final SamplesView SAMPLES_VIEW = SamplesView.SAMPLES_VIEW;

    /**
     * The table <code>selected_events</code>.
     */
    public static final SelectedEvents SELECTED_EVENTS = SelectedEvents.SELECTED_EVENTS;

    /**
     * The table <code>symbols</code>.
     */
    public static final Symbols SYMBOLS = Symbols.SYMBOLS;

    /**
     * The table <code>symbols_view</code>.
     */
    public static final SymbolsView SYMBOLS_VIEW = SymbolsView.SYMBOLS_VIEW;

    /**
     * The table <code>threads</code>.
     */
    public static final Threads THREADS = Threads.THREADS;

    /**
     * The table <code>threads_view</code>.
     */
    public static final ThreadsView THREADS_VIEW = ThreadsView.THREADS_VIEW;
}
