/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables.references


import com.perfscope.model.tables.BranchTypes
import com.perfscope.model.tables.CallPaths
import com.perfscope.model.tables.CallPathsView
import com.perfscope.model.tables.Calls
import com.perfscope.model.tables.CallsView
import com.perfscope.model.tables.Cbr
import com.perfscope.model.tables.CbrView
import com.perfscope.model.tables.CommThreads
import com.perfscope.model.tables.CommThreadsView
import com.perfscope.model.tables.Comms
import com.perfscope.model.tables.ContextSwitches
import com.perfscope.model.tables.ContextSwitchesView
import com.perfscope.model.tables.Dsos
import com.perfscope.model.tables.DsosView
import com.perfscope.model.tables.Machines
import com.perfscope.model.tables.MachinesView
import com.perfscope.model.tables.Samples
import com.perfscope.model.tables.SamplesView
import com.perfscope.model.tables.SelectedEvents
import com.perfscope.model.tables.Symbols
import com.perfscope.model.tables.SymbolsView
import com.perfscope.model.tables.Threads
import com.perfscope.model.tables.ThreadsView



/**
 * The table <code>branch_types</code>.
 */
val BRANCH_TYPES: BranchTypes = BranchTypes.BRANCH_TYPES

/**
 * The table <code>call_paths</code>.
 */
val CALL_PATHS: CallPaths = CallPaths.CALL_PATHS

/**
 * The table <code>call_paths_view</code>.
 */
val CALL_PATHS_VIEW: CallPathsView = CallPathsView.CALL_PATHS_VIEW

/**
 * The table <code>calls</code>.
 */
val CALLS: Calls = Calls.CALLS

/**
 * The table <code>calls_view</code>.
 */
val CALLS_VIEW: CallsView = CallsView.CALLS_VIEW

/**
 * The table <code>cbr</code>.
 */
val CBR: Cbr = Cbr.CBR

/**
 * The table <code>cbr_view</code>.
 */
val CBR_VIEW: CbrView = CbrView.CBR_VIEW

/**
 * The table <code>comm_threads</code>.
 */
val COMM_THREADS: CommThreads = CommThreads.COMM_THREADS

/**
 * The table <code>comm_threads_view</code>.
 */
val COMM_THREADS_VIEW: CommThreadsView = CommThreadsView.COMM_THREADS_VIEW

/**
 * The table <code>comms</code>.
 */
val COMMS: Comms = Comms.COMMS

/**
 * The table <code>context_switches</code>.
 */
val CONTEXT_SWITCHES: ContextSwitches = ContextSwitches.CONTEXT_SWITCHES

/**
 * The table <code>context_switches_view</code>.
 */
val CONTEXT_SWITCHES_VIEW: ContextSwitchesView = ContextSwitchesView.CONTEXT_SWITCHES_VIEW

/**
 * The table <code>dsos</code>.
 */
val DSOS: Dsos = Dsos.DSOS

/**
 * The table <code>dsos_view</code>.
 */
val DSOS_VIEW: DsosView = DsosView.DSOS_VIEW

/**
 * The table <code>machines</code>.
 */
val MACHINES: Machines = Machines.MACHINES

/**
 * The table <code>machines_view</code>.
 */
val MACHINES_VIEW: MachinesView = MachinesView.MACHINES_VIEW

/**
 * The table <code>samples</code>.
 */
val SAMPLES: Samples = Samples.SAMPLES

/**
 * The table <code>samples_view</code>.
 */
val SAMPLES_VIEW: SamplesView = SamplesView.SAMPLES_VIEW

/**
 * The table <code>selected_events</code>.
 */
val SELECTED_EVENTS: SelectedEvents = SelectedEvents.SELECTED_EVENTS

/**
 * The table <code>symbols</code>.
 */
val SYMBOLS: Symbols = Symbols.SYMBOLS

/**
 * The table <code>symbols_view</code>.
 */
val SYMBOLS_VIEW: SymbolsView = SymbolsView.SYMBOLS_VIEW

/**
 * The table <code>threads</code>.
 */
val THREADS: Threads = Threads.THREADS

/**
 * The table <code>threads_view</code>.
 */
val THREADS_VIEW: ThreadsView = ThreadsView.THREADS_VIEW
