/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CallPaths implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final Long parentId;
    private final Long symbolId;
    private final Long ip;

    public CallPaths(CallPaths value) {
        this.id = value.id;
        this.parentId = value.parentId;
        this.symbolId = value.symbolId;
        this.ip = value.ip;
    }

    public CallPaths(
        Integer id,
        Long parentId,
        Long symbolId,
        Long ip
    ) {
        this.id = id;
        this.parentId = parentId;
        this.symbolId = symbolId;
        this.ip = ip;
    }

    /**
     * Getter for <code>call_paths.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>call_paths.parent_id</code>.
     */
    public Long getParentId() {
        return this.parentId;
    }

    /**
     * Getter for <code>call_paths.symbol_id</code>.
     */
    public Long getSymbolId() {
        return this.symbolId;
    }

    /**
     * Getter for <code>call_paths.ip</code>.
     */
    public Long getIp() {
        return this.ip;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CallPaths other = (CallPaths) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.parentId == null) {
            if (other.parentId != null)
                return false;
        }
        else if (!this.parentId.equals(other.parentId))
            return false;
        if (this.symbolId == null) {
            if (other.symbolId != null)
                return false;
        }
        else if (!this.symbolId.equals(other.symbolId))
            return false;
        if (this.ip == null) {
            if (other.ip != null)
                return false;
        }
        else if (!this.ip.equals(other.ip))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.parentId == null) ? 0 : this.parentId.hashCode());
        result = prime * result + ((this.symbolId == null) ? 0 : this.symbolId.hashCode());
        result = prime * result + ((this.ip == null) ? 0 : this.ip.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CallPaths (");

        sb.append(id);
        sb.append(", ").append(parentId);
        sb.append(", ").append(symbolId);
        sb.append(", ").append(ip);

        sb.append(")");
        return sb.toString();
    }
}
