/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables.records


import com.perfscope.model.tables.CallPaths

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CallPathsRecord() : UpdatableRecordImpl<CallPathsRecord>(CallPaths.CALL_PATHS) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var parentId: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var symbolId: Long?
        set(value): Unit = set(2, value)
        get(): Long? = get(2) as Long?

    open var ip: Long?
        set(value): Unit = set(3, value)
        get(): Long? = get(3) as Long?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised CallPathsRecord
     */
    constructor(id: Int? = null, parentId: Long? = null, symbolId: Long? = null, ip: Long? = null): this() {
        this.id = id
        this.parentId = parentId
        this.symbolId = symbolId
        this.ip = ip
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised CallPathsRecord
     */
    constructor(value: com.perfscope.model.tables.pojos.CallPaths?): this() {
        if (value != null) {
            this.id = value.id
            this.parentId = value.parentId
            this.symbolId = value.symbolId
            this.ip = value.ip
            resetChangedOnNotNull()
        }
    }
}
