/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables.records


import com.perfscope.model.tables.CallPathsView

import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CallPathsViewRecord() : TableRecordImpl<CallPathsViewRecord>(CallPathsView.CALL_PATHS_VIEW) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var ip: Any?
        set(value): Unit = set(1, value)
        get(): Any? = get(1) as Any?

    open var symbolId: Long?
        set(value): Unit = set(2, value)
        get(): Long? = get(2) as Long?

    open var symbol: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var dsoId: Long?
        set(value): Unit = set(4, value)
        get(): Long? = get(4) as Long?

    open var dsoShortName: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var parentId: Long?
        set(value): Unit = set(6, value)
        get(): Long? = get(6) as Long?

    open var parentIp: Any?
        set(value): Unit = set(7, value)
        get(): Any? = get(7) as Any?

    open var parentSymbolId: Long?
        set(value): Unit = set(8, value)
        get(): Long? = get(8) as Long?

    open var parentSymbol: String?
        set(value): Unit = set(9, value)
        get(): String? = get(9) as String?

    open var parentDsoId: Long?
        set(value): Unit = set(10, value)
        get(): Long? = get(10) as Long?

    open var parentDsoShortName: String?
        set(value): Unit = set(11, value)
        get(): String? = get(11) as String?

    /**
     * Create a detached, initialised CallPathsViewRecord
     */
    constructor(id: Int? = null, ip: Any? = null, symbolId: Long? = null, symbol: String? = null, dsoId: Long? = null, dsoShortName: String? = null, parentId: Long? = null, parentIp: Any? = null, parentSymbolId: Long? = null, parentSymbol: String? = null, parentDsoId: Long? = null, parentDsoShortName: String? = null): this() {
        this.id = id
        this.ip = ip
        this.symbolId = symbolId
        this.symbol = symbol
        this.dsoId = dsoId
        this.dsoShortName = dsoShortName
        this.parentId = parentId
        this.parentIp = parentIp
        this.parentSymbolId = parentSymbolId
        this.parentSymbol = parentSymbol
        this.parentDsoId = parentDsoId
        this.parentDsoShortName = parentDsoShortName
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised CallPathsViewRecord
     */
    constructor(value: com.perfscope.model.tables.pojos.CallPathsView?): this() {
        if (value != null) {
            this.id = value.id
            this.ip = value.ip
            this.symbolId = value.symbolId
            this.symbol = value.symbol
            this.dsoId = value.dsoId
            this.dsoShortName = value.dsoShortName
            this.parentId = value.parentId
            this.parentIp = value.parentIp
            this.parentSymbolId = value.parentSymbolId
            this.parentSymbol = value.parentSymbol
            this.parentDsoId = value.parentDsoId
            this.parentDsoShortName = value.parentDsoShortName
            resetChangedOnNotNull()
        }
    }
}
