/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables.records


import com.perfscope.model.tables.Cbr

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CbrRecord() : UpdatableRecordImpl<CbrRecord>(Cbr.CBR) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var cbr: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var mhz: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    open var percent: Int?
        set(value): Unit = set(3, value)
        get(): Int? = get(3) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised CbrRecord
     */
    constructor(id: Int? = null, cbr: Int? = null, mhz: Int? = null, percent: Int? = null): this() {
        this.id = id
        this.cbr = cbr
        this.mhz = mhz
        this.percent = percent
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised CbrRecord
     */
    constructor(value: com.perfscope.model.tables.pojos.Cbr?): this() {
        if (value != null) {
            this.id = value.id
            this.cbr = value.cbr
            this.mhz = value.mhz
            this.percent = value.percent
            resetChangedOnNotNull()
        }
    }
}
