/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables.records


import com.perfscope.model.tables.CbrView

import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CbrViewRecord() : TableRecordImpl<CbrViewRecord>(CbrView.CBR_VIEW) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var time: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var cpu: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    open var cbr: Int?
        set(value): Unit = set(3, value)
        get(): Int? = get(3) as Int?

    open var mhz: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var percent: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    /**
     * Create a detached, initialised CbrViewRecord
     */
    constructor(id: Int? = null, time: Long? = null, cpu: Int? = null, cbr: Int? = null, mhz: Int? = null, percent: Int? = null): this() {
        this.id = id
        this.time = time
        this.cpu = cpu
        this.cbr = cbr
        this.mhz = mhz
        this.percent = percent
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised CbrViewRecord
     */
    constructor(value: com.perfscope.model.tables.pojos.CbrView?): this() {
        if (value != null) {
            this.id = value.id
            this.time = value.time
            this.cpu = value.cpu
            this.cbr = value.cbr
            this.mhz = value.mhz
            this.percent = value.percent
            resetChangedOnNotNull()
        }
    }
}
