/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables.records


import com.perfscope.model.tables.Comms

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CommsRecord() : UpdatableRecordImpl<CommsRecord>(Comms.COMMS) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var comm: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var cThreadId: Long?
        set(value): Unit = set(2, value)
        get(): Long? = get(2) as Long?

    open var cTime: Long?
        set(value): Unit = set(3, value)
        get(): Long? = get(3) as Long?

    open var execFlag: Boolean?
        set(value): Unit = set(4, value)
        get(): Boolean? = get(4) as Boolean?

    open var hasCalls: Boolean?
        set(value): Unit = set(5, value)
        get(): Boolean? = get(5) as Boolean?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised CommsRecord
     */
    constructor(id: Int? = null, comm: String? = null, cThreadId: Long? = null, cTime: Long? = null, execFlag: Boolean? = null, hasCalls: Boolean? = null): this() {
        this.id = id
        this.comm = comm
        this.cThreadId = cThreadId
        this.cTime = cTime
        this.execFlag = execFlag
        this.hasCalls = hasCalls
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised CommsRecord
     */
    constructor(value: com.perfscope.model.tables.pojos.Comms?): this() {
        if (value != null) {
            this.id = value.id
            this.comm = value.comm
            this.cThreadId = value.cThreadId
            this.cTime = value.cTime
            this.execFlag = value.execFlag
            this.hasCalls = value.hasCalls
            resetChangedOnNotNull()
        }
    }
}
