/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables.records


import com.perfscope.model.tables.ContextSwitchesView

import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ContextSwitchesViewRecord() : TableRecordImpl<ContextSwitchesViewRecord>(ContextSwitchesView.CONTEXT_SWITCHES_VIEW) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var machineId: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var time: Long?
        set(value): Unit = set(2, value)
        get(): Long? = get(2) as Long?

    open var cpu: Int?
        set(value): Unit = set(3, value)
        get(): Int? = get(3) as Int?

    open var pidOut: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var tidOut: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    open var commOut: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var pidIn: Int?
        set(value): Unit = set(7, value)
        get(): Int? = get(7) as Int?

    open var tidIn: Int?
        set(value): Unit = set(8, value)
        get(): Int? = get(8) as Int?

    open var commIn: String?
        set(value): Unit = set(9, value)
        get(): String? = get(9) as String?

    open var flags: String?
        set(value): Unit = set(10, value)
        get(): String? = get(10) as String?

    /**
     * Create a detached, initialised ContextSwitchesViewRecord
     */
    constructor(id: Int? = null, machineId: Long? = null, time: Long? = null, cpu: Int? = null, pidOut: Int? = null, tidOut: Int? = null, commOut: String? = null, pidIn: Int? = null, tidIn: Int? = null, commIn: String? = null, flags: String? = null): this() {
        this.id = id
        this.machineId = machineId
        this.time = time
        this.cpu = cpu
        this.pidOut = pidOut
        this.tidOut = tidOut
        this.commOut = commOut
        this.pidIn = pidIn
        this.tidIn = tidIn
        this.commIn = commIn
        this.flags = flags
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised ContextSwitchesViewRecord
     */
    constructor(value: com.perfscope.model.tables.pojos.ContextSwitchesView?): this() {
        if (value != null) {
            this.id = value.id
            this.machineId = value.machineId
            this.time = value.time
            this.cpu = value.cpu
            this.pidOut = value.pidOut
            this.tidOut = value.tidOut
            this.commOut = value.commOut
            this.pidIn = value.pidIn
            this.tidIn = value.tidIn
            this.commIn = value.commIn
            this.flags = value.flags
            resetChangedOnNotNull()
        }
    }
}
