/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables.records


import com.perfscope.model.tables.DsosView

import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DsosViewRecord() : TableRecordImpl<DsosViewRecord>(DsosView.DSOS_VIEW) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var machineId: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var hostOrGuest: Any?
        set(value): Unit = set(2, value)
        get(): Any? = get(2) as Any?

    open var shortName: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var longName: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var buildId: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    /**
     * Create a detached, initialised DsosViewRecord
     */
    constructor(id: Int? = null, machineId: Long? = null, hostOrGuest: Any? = null, shortName: String? = null, longName: String? = null, buildId: String? = null): this() {
        this.id = id
        this.machineId = machineId
        this.hostOrGuest = hostOrGuest
        this.shortName = shortName
        this.longName = longName
        this.buildId = buildId
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised DsosViewRecord
     */
    constructor(value: com.perfscope.model.tables.pojos.DsosView?): this() {
        if (value != null) {
            this.id = value.id
            this.machineId = value.machineId
            this.hostOrGuest = value.hostOrGuest
            this.shortName = value.shortName
            this.longName = value.longName
            this.buildId = value.buildId
            resetChangedOnNotNull()
        }
    }
}
