/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables.records


import com.perfscope.model.tables.Machines

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class MachinesRecord() : UpdatableRecordImpl<MachinesRecord>(Machines.MACHINES) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var pid: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var rootDir: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised MachinesRecord
     */
    constructor(id: Int? = null, pid: Int? = null, rootDir: String? = null): this() {
        this.id = id
        this.pid = pid
        this.rootDir = rootDir
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised MachinesRecord
     */
    constructor(value: com.perfscope.model.tables.pojos.Machines?): this() {
        if (value != null) {
            this.id = value.id
            this.pid = value.pid
            this.rootDir = value.rootDir
            resetChangedOnNotNull()
        }
    }
}
