/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables.records


import com.perfscope.model.tables.SamplesView

import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SamplesViewRecord() : TableRecordImpl<SamplesViewRecord>(SamplesView.SAMPLES_VIEW) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var time: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var cpu: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    open var pid: Int?
        set(value): Unit = set(3, value)
        get(): Int? = get(3) as Int?

    open var tid: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var command: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var event: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var ipHex: Any?
        set(value): Unit = set(7, value)
        get(): Any? = get(7) as Any?

    open var symbol: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    open var symOffset: Long?
        set(value): Unit = set(9, value)
        get(): Long? = get(9) as Long?

    open var dsoShortName: String?
        set(value): Unit = set(10, value)
        get(): String? = get(10) as String?

    open var toIpHex: Any?
        set(value): Unit = set(11, value)
        get(): Any? = get(11) as Any?

    open var toSymbol: String?
        set(value): Unit = set(12, value)
        get(): String? = get(12) as String?

    open var toSymOffset: Long?
        set(value): Unit = set(13, value)
        get(): Long? = get(13) as Long?

    open var toDsoShortName: String?
        set(value): Unit = set(14, value)
        get(): String? = get(14) as String?

    open var branchTypeName: String?
        set(value): Unit = set(15, value)
        get(): String? = get(15) as String?

    open var inTx: Boolean?
        set(value): Unit = set(16, value)
        get(): Boolean? = get(16) as Boolean?

    open var insnCount: Long?
        set(value): Unit = set(17, value)
        get(): Long? = get(17) as Long?

    open var cycCount: Long?
        set(value): Unit = set(18, value)
        get(): Long? = get(18) as Long?

    open var ipc: Any?
        set(value): Unit = set(19, value)
        get(): Any? = get(19) as Any?

    open var flags: Int?
        set(value): Unit = set(20, value)
        get(): Int? = get(20) as Int?

    /**
     * Create a detached, initialised SamplesViewRecord
     */
    constructor(id: Int? = null, time: Long? = null, cpu: Int? = null, pid: Int? = null, tid: Int? = null, command: String? = null, event: String? = null, ipHex: Any? = null, symbol: String? = null, symOffset: Long? = null, dsoShortName: String? = null, toIpHex: Any? = null, toSymbol: String? = null, toSymOffset: Long? = null, toDsoShortName: String? = null, branchTypeName: String? = null, inTx: Boolean? = null, insnCount: Long? = null, cycCount: Long? = null, ipc: Any? = null, flags: Int? = null): this() {
        this.id = id
        this.time = time
        this.cpu = cpu
        this.pid = pid
        this.tid = tid
        this.command = command
        this.event = event
        this.ipHex = ipHex
        this.symbol = symbol
        this.symOffset = symOffset
        this.dsoShortName = dsoShortName
        this.toIpHex = toIpHex
        this.toSymbol = toSymbol
        this.toSymOffset = toSymOffset
        this.toDsoShortName = toDsoShortName
        this.branchTypeName = branchTypeName
        this.inTx = inTx
        this.insnCount = insnCount
        this.cycCount = cycCount
        this.ipc = ipc
        this.flags = flags
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised SamplesViewRecord
     */
    constructor(value: com.perfscope.model.tables.pojos.SamplesView?): this() {
        if (value != null) {
            this.id = value.id
            this.time = value.time
            this.cpu = value.cpu
            this.pid = value.pid
            this.tid = value.tid
            this.command = value.command
            this.event = value.event
            this.ipHex = value.ipHex
            this.symbol = value.symbol
            this.symOffset = value.symOffset
            this.dsoShortName = value.dsoShortName
            this.toIpHex = value.toIpHex
            this.toSymbol = value.toSymbol
            this.toSymOffset = value.toSymOffset
            this.toDsoShortName = value.toDsoShortName
            this.branchTypeName = value.branchTypeName
            this.inTx = value.inTx
            this.insnCount = value.insnCount
            this.cycCount = value.cycCount
            this.ipc = value.ipc
            this.flags = value.flags
            resetChangedOnNotNull()
        }
    }
}
