/*
 * This file is generated by jOOQ.
 */
package com.perfscope.model.tables.records


import com.perfscope.model.tables.ThreadsView

import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ThreadsViewRecord() : TableRecordImpl<ThreadsViewRecord>(ThreadsView.THREADS_VIEW) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var machineId: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var hostOrGuest: Any?
        set(value): Unit = set(2, value)
        get(): Any? = get(2) as Any?

    open var processId: Long?
        set(value): Unit = set(3, value)
        get(): Long? = get(3) as Long?

    open var pid: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var tid: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    /**
     * Create a detached, initialised ThreadsViewRecord
     */
    constructor(id: Int? = null, machineId: Long? = null, hostOrGuest: Any? = null, processId: Long? = null, pid: Int? = null, tid: Int? = null): this() {
        this.id = id
        this.machineId = machineId
        this.hostOrGuest = hostOrGuest
        this.processId = processId
        this.pid = pid
        this.tid = tid
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised ThreadsViewRecord
     */
    constructor(value: com.perfscope.model.tables.pojos.ThreadsView?): this() {
        if (value != null) {
            this.id = value.id
            this.machineId = value.machineId
            this.hostOrGuest = value.hostOrGuest
            this.processId = value.processId
            this.pid = value.pid
            this.tid = value.tid
            resetChangedOnNotNull()
        }
    }
}
